package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Temp1_TempConfig1'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Temp1_TempConfig1")) {
    expectSteps {
        script {
            scriptContent = "qeqwe"
        }
    }
    steps {
        insert(1) {
            powerShell {
                name = "sdf"
                scriptMode = script {
                    content = "sdf"
                }
            }
        }
    }
}
